name: digital_certificate
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.15.0
  cloud_functions: ^4.6.0
  google_sign_in: ^6.2.1
  cupertino_icons: ^1.0.8
  file_picker: ^8.0.7
  google_mlkit_text_recognition: ^0.15.0
  flutter_spinkit: ^5.2.1
  firebase_storage: ^11.6.7
  pdf: ^3.10.4
  path_provider: ^2.1.2
  url_launcher: ^6.1.7
  open_file: ^3.3.2
  flutterfire_cli: ^1.3.1
  flutter_stripe: ^10.1.0
  shared_preferences: ^2.2.2
  uuid: ^4.3.3
  http: ^1.1.2
  intl: ^0.18.1
  google_fonts: ^6.2.1
  share_plus: ^7.2.1
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
