// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9kxQV3FtMNPVahqZxmxPVZfUBTtQ0AQc',
    appId: '1:330628707805:web:ebd2bbf1e0113e58e0b234',
    messagingSenderId: '330628707805',
    projectId: 'digital-certificate-1a462',
    authDomain: 'digital-certificate-1a462.firebaseapp.com',
    storageBucket: 'digital-certificate-1a462.firebasestorage.app',
    measurementId: 'G-P0NREJRHRR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7ykw3Tob9LeZviNTdH1b2bFVGAJ-WzQQ',
    appId: '1:330628707805:android:f27af53b343e815ee0b234',
    messagingSenderId: '330628707805',
    projectId: 'digital-certificate-1a462',
    storageBucket: 'digital-certificate-1a462.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkdeom-or9rAfChXh1gE12eITkm_dTM3w',
    appId: '1:330628707805:ios:42aae56e2382eed1e0b234',
    messagingSenderId: '330628707805',
    projectId: 'digital-certificate-1a462',
    storageBucket: 'digital-certificate-1a462.firebasestorage.app',
    iosBundleId: 'com.example.digitalCertificate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkdeom-or9rAfChXh1gE12eITkm_dTM3w',
    appId: '1:330628707805:ios:42aae56e2382eed1e0b234',
    messagingSenderId: '330628707805',
    projectId: 'digital-certificate-1a462',
    storageBucket: 'digital-certificate-1a462.firebasestorage.app',
    iosBundleId: 'com.example.digitalCertificate',
  );
}
